name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 623e7cba2276d70bee3c08e73c0bc229
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
